# Generated by Django 5.0.4 on 2024-05-02 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_control', models.CharField(max_length=100)),
                ('sub_control', models.CharField(max_length=100)),
                ('likelihood', models.CharField(max_length=20)),
                ('impact', models.CharField(max_length=20)),
                ('exposure', models.CharField(max_length=20)),
                ('risk_level', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
