# Generated by Django 5.0.4 on 2024-05-02 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment_project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='exposure',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='impact',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='likelihood',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='riskassessment',
            name='sub_control',
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='control_details',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='subcontrol',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='riskassessment',
            name='main_control',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.CreateModel(
            name='UserAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likelihood', models.CharField(default='', max_length=5000)),
                ('impact', models.CharField(default='', max_length=5000)),
                ('exposure', models.CharField(default='', max_length=5000)),
                ('risk_level', models.CharField(default='', max_length=5000)),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='risk_assessment_project.riskassessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
