# Generated by Django 5.0.4 on 2024-05-02 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment_project', '0002_remove_riskassessment_exposure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskassessment',
            name='user',
        ),
    ]
