# Generated by Django 5.0.4 on 2024-05-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment_project', '0003_remove_riskassessment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userassessment',
            name='exposure',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='impact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userassessment',
            name='likelihood',
            field=models.IntegerField(default=0),
        ),
    ]
