# Generated by Django 5.0.4 on 2024-05-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment_project', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
