# Generated by Django 5.0.4 on 2024-05-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment_project', '0006_riskassessment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskassessment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
