# Generated by Django 5.0.4 on 2024-05-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk_assessment_project', '0007_alter_riskassessment_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riskassessment',
            old_name='status',
            new_name='statu',
        ),
    ]
